# all paths are relative to yaml/execution?
# TODO: naming/structure will need to be improved
overall:
  name: 'cats vs dogs'
  #verbosity: 0
  print_graph_spec: True
  #tf_log_level: 'warn' # TODO: use
  # will need to investigate disabling cudnn > nondeterministic backprop
  #deterministic: null # not currently possible
  #rand_seed: 42 # TODO: use
  # regression, segmentation, GAN, autoencode
  type: 'sigmoid'
  #report_level: 1 # use to print model arch (output size)
  # trace: 'full'
  # performance:
  #   # default (auc, acc,loss)
  #   eval:
  #     - 'sensitivity'
  #     - 'precision'
  #     - 'F1'
data:
  in: 
    dim: [150, 150, 3]
    dtype: 'float32'
    #reshape_to: [28, 28, 1] # TODO: use
  label:
    dim: [1]
    dtype: 'int64'
  TFR: 
    dir: './example/cats_v_dogs_01/data/record_holder/150'
    train: 'train.tfrecords'
    validation: 'validation.tfrecords'
    test: 'test.tfrecords'
  # TODO: train/val/test split, kfold?
  # TODO: augmentation?
  # TODO: preprocessing
saver:
  # pickel-ed-params
  save_pparams: 'best_params' # required
  #load_pparams: null
  #save_graph: null
  # if load model, then the architecture+implementation is void
  #load_graph: null
tensorboard:
  # if null, a default location will be created/selected
  log_dir: 'trial_01'
hyper_parameters:
  optimizer: 'adam'
  lr: 0.00001
  batch_size: 16
  epochs: 3 # for quick testing
  default_activation: 'elu'
  shuffle_buffer: 128
  early_stopping:
    epochs: 2
    warm_up_epochs: 5
hidden:
  # TODO: maybe this could also be a .py file containing a graph
  # > (clear input/output would need to be defined)
  yaml: './example/cats_v_dogs_01/hidden_config.yaml'
train:
  image_standardize: True
  # augmentation:
  #   aug_val: True
  #   v_flip: True
  #   h_flip: True
  #   #rotate: 0
  #   max_brightness: 0.2
