# documentation will be key - "sane" defaults
# key: value
# key will be the "name" of the layer, value will hold the type+
# TODO: set *NECESSARTY/REQUIRED* params

# TODO: initialization
# TODO: option to write scalar
# TODO: default conv = conv2d?
# TODO: default strides = 1, padding='SAME'
# TODO: regularization

layers:
  dense_1:
    type: 'dense'
    options:
      units: 64
  dropout_1:
    type: 'dropout'
    options:
      rate: 0.5
  dense_2:
    type: 'dense'
    options:
      units: 32
  dropout_2:
    type: 'dropout'
    options:
      rate: 0.5
  dense_3:
    type: 'dense'
    options:
      units: 32
  dropout_3:
    type: 'dropout'
    options:
      rate: 0.5
  dense_4:
    type: 'dense'
    options:
      units: 16
  dropout_4:
    type: 'dropout'
    options:
      rate: 0.5
  dense_5:
    type: 'dense'
    options:
      units: 16
  dense_out:
    type: 'dense'
    options:
      units: 1
