# all paths are relative to yaml/execution?
# TODO: naming/structure will need to be improved
overall:
  name: 'cali_housing'
  loss_fn: 
    type: 'mean_squared_error'
  experiment_dir: 'trial_01' # will make + /best_params/ and + /tf_logs/ + /yf_logs/
  saver:
    save_params_name: "best_params_saver"
  logging:
    console:
      level: 'info'
    file:
      level: 'ERROR'
    graph_spec: True
  metrics:
    type: ['MeanAbsoluteError']
data:
  in: 
    dim: [8]
    dtype: 'float32'
  label:
    dim: [1]
    dtype: 'float32'
  TFR_parse:
    feature:
      name: "/features"
      dtype: "float32"
      tftype: "FixedLenSequenceFeature"
      in_type: "float32"
    label:
      name: "/label"
      dtype: "float32" # what to decode it to
      tftype: "fixedlenfeature"
      in_type: "float32" # what it is encoded as
  TFR:
    dir: './examples/cali_housing/data/'
    train: 'final_train.tfrecords'
    validation: 'final_validation.tfrecords'
    test: 'final_test.tfrecords'
hyper_parameters:
  optimizer: 
    type: 'adam'
    learning_rate: 0.005
  batch_size: 32
  epochs: 20 # 200 epochs = 3:47min on 1080ti, 5epocs = ~5sec on cpu
  default_activation: 
    type: 'elu'
  shuffle_buffer: 128
  # early_stopping:
  #   epochs: 10
  #   warm_up_epochs: 5
hidden:
  # TODO: maybe this could also be a .py file containing a graph
  # > (clear input/output would need to be defined)
  path: './examples/cali_housing/hidden_config.yaml'
 