# all paths are relative to yaml/execution?
# TODO: naming/structure will need to be improved
overall:
  name: 'cali_housing'
  loss_fn: 'RMSE'
  experiment_dir: 'trial_01' # will make + /best_params/ and + /tf_logs/ + /yf_logs/
  saver:
    save_params_name: "best_params_saver"
  logging:
    console:
      level: 'critical'
    file:
      level: 'debug'
    graph_spec: True
  metrics:
    type: 'regression'
data:
  in: 
    dim: [8]
    dtype: 'float32'
  label:
    dim: [1]
    dtype: 'float32'
  TFR:
    dir: './examples/cali_housing/data/'
    train: 'train.tfrecords'
    validation: 'validation.tfrecords'
    test: 'test.tfrecords'
hyper_parameters:
  optimizer: 'adam'
  lr: 0.003
  batch_size: 32
  epochs: 5 # 200 epochs = 3:47min on 1080ti, 5 = ~5sec on cpu
  default_activation: 'elu'
  shuffle_buffer: 128
  early_stopping:
    epochs: 10
    warm_up_epochs: 5
hidden:
  # TODO: maybe this could also be a .py file containing a graph
  # > (clear input/output would need to be defined)
  yaml: './examples/cali_housing/hidden_config.yaml'
 