overall:
  name: 'cats vs dogs'
  print_graph_spec: True
  options: 'softmax'
  trace: 'full'
data:
  in: 
    dim: [784]
    dtype: 'float32'
    reshape_to: [28, 28, 1]
  label:
    dim: [10]
    dtype: 'float32'
  TFR:
    dir: './example/mnist/data/'
    train: 'train.tfrecords'
    validation: 'validation.tfrecords'
    test: 'test.tfrecords'
saver:
  save_pparams: 'best_params' # location to save best params
tensorboard:
  log_dir: 'trial_01'
hyper_parameters:
  lr: 0.00001
  batch_size: 16
  epochs: 10
  optimizer: 'adam'
  default_activation: 'elu'
  shuffle_buffer: 128
architecture:
  yaml: './path/to/hidden_config.yaml'
train:
  image_standardize: True
  augmentation:
    aug_val: True
    v_flip: True
    h_flip: True
    max_brightness: 0.2