# all paths are relative to yaml/execution?
# TODO: naming/structure will need to be improved
overall:
  name: 'mnist'
  print_graph_spec: True
  type: 'classification_multi'
  # trace: Null
data:
  in: 
    dim: [784]
    dtype: 'float32'
    reshape_to: [28, 28, 1] # TODO: use
  label:
    dim: [10]
    dtype: 'float32'
  TFR:
    dir: './example/mnist/data/'
    train: 'train.tfrecords'
    validation: 'validation.tfrecords'
    test: 'test.tfrecords'
saver:
  # pickel-ed-params
  save_pparams: 'best_params' # required
tensorboard:
  log_dir: 'trial_01'
hyper_parameters:
  optimizer: 'adam'
  lr: 0.0001
  batch_size: 32
  epochs: 8
  default_activation: 'elu'
  shuffle_buffer: 128
  # early_stopping:
  #   epochs: 3
  #   warm_up_epochs: 5
hidden:
  # TODO: maybe this could also be a .py file containing a graph
  # > (clear input/output would need to be defined)
  yaml: './example/mnist/hidden_config.yaml'
# train:
#   image_standardize: True
  # augmentation:
  #   aug_val: True
  #   v_flip: True
  #   h_flip: True
  #   #rotate: 0
  #   max_brightness: 0.2