meta:
  name: 'abalone'
  experiment_dir: 'trial_00'
  # TODO: information on when to save params, currently only best params saved
logging:
  console:
    level: 'info'
    format_str: null
  file:
    level: 'ERROR'
    format_str: null
  graph_spec: True

performance:
  loss_fn: 
    type: 'MSE'
  type: ["MeanSquaredError", "MeanAbsoluteError"]
  options: [null, 
            null]

# TODO: this section needs to be redone
data:
  in:
    dim: [1]
    dtype: 'float64'
  label:
    dim: [1]
    dtype: 'float64'

hyper_parameters:
  optimizer: 
    type: 'adam'
    learning_rate: 0.0001
  batch_size: 32
  epochs: 10
  shuffle_buffer: 128
model:
  path: './examples/abalone/model_config.yml'

