name: "model_a"
start_fresh: True

# TODO: it could be assumed that if only one layer in is defined in main, that
# it could be the `in_name` to the first layer.
layers:
  conv_1:
    type: "conv2d"
    options:
      filters: 8
      kernel_size: 3
      padding: "same"
      activation:
        type: elu
    in_name: "x_image"
  conv_2_downsample:
    type: "conv2d"
    options:
      filters: 16
      kernel_size: 3
      strides: 2
      padding: "same" # 14,14,n
      activation:
        type: elu
  conv_3:
    type: "conv2d"
    options:
      filters: 16
      kernel_size: 3
      strides: 1
      padding: "same"
      activation:
        type: elu
  conv_4_downsample:
    type: "conv2d"
    options:
      filters: 32
      kernel_size: 3
      strides: 2
      padding: "same" # 7,7,n
      activation:
        type: elu
  conv_5_upsample:
    type: "Conv2DTranspose"
    options:
      filters: 32
      kernel_size: 3
      strides: 2
      padding: "same" # 14,14,n
      activation:
        type: elu
  conv_6_upsample:
    type: "conv2d"
    options:
      filters: 16
      kernel_size: 3
      strides: 1
      padding: "same"
      activation:
        type: elu
  conv_7_upsample:
    type: "Conv2DTranspose"
    options:
      filters: 16
      kernel_size: 3
      strides: 2
      padding: "same" # 28,28,n
      activation:
        type: elu
  conv_8_upsample:
    type: "conv2d"
    options:
      filters: 8
      kernel_size: 3
      strides: 1
      padding: "same"
      activation:
        type: elu
  conv_compress:
    type: "conv2d"
    options:
      filters: 3
      kernel_size: 1
      strides: 1
      padding: "same"
      activation:
        type: elu
  y_pred:
    type: "conv2d"
    options:
      filters: 1
      kernel_size: 1
      strides: 1
      padding: "same"
      activation:
        type: sigmoid
    endpoint: True
