# all paths are relative to yaml/execution?
# TODO: naming/structure will need to be improved
overall:
  name: 'multi_segmentation'
  loss_fn: 'softmax_multi_segmentation_temp' # TODO: this will need to be fixed
  experiment_dir: 'trial_01' # will make + /best_params/ and + /tf_logs/ + /yf_logs/
  saver:
    save_params_name: "best_params_saver"
  logging:
    console:
      level: 'critical'
    file:
      level: 'debug'
    graph_spec: True
  metrics:
    type: 'segmentation'
  num_classes: 9
  class_names: ['background','general_face','eyes','lips','nose','ears','eyebrows','teeth','hair'] # TODO: include
  class_weights: [1.0, 1.71, 208.99, 101.53, 41.71, 72.78, 143.15, 641.36, 8.94]
data:
  in:
    dim: [280, 300, 3]
    dtype: 'float32'
  label:
    dim: [280, 300]
    dtype: 'int32'
  TFR_parse:
    feature:
      name: "/image"
      dtype: "float32"
      tftype: "fixedlenfeature"
      in_type: "string"
    label:
      name: "/label"
      dtype: "int32"
      tftype: "fixedlenfeature"
      in_type: "string"
  TFR:
    dir: './examples/multi_segmentation/data/multi'
    train: 'train.tfrecords'
    validation: 'validation.tfrecords'
    test: 'test.tfrecords'
hyper_parameters:
  optimizer: 'adam'
  lr: 0.0001
  batch_size: 12
  epochs: 250 # 200 epochs = 3:47min on 1080ti, 5 = ~5sec on cpu
  default_activation: 'elu'
  shuffle_buffer: 100
  early_stopping:
    epochs: 50
    warm_up_epochs: 15
hidden:
  # TODO: maybe this could also be a .py file containing a graph
  # > (clear input/output would need to be defined)
  path: './examples/multi_segmentation/hidden_config.yaml'
train:
  augmentation:
    label: True # TODO: temp
    aug_val: True
    v_flip: True
    h_flip: True
 