# documentation will be key - "sane" defaults
# key: value
# key will be the "name" of the layer, value will hold the type+
# TODO: set *NECESSARTY/REQUIRED* params

# TODO: initialization
# TODO: option to write scalar
# TODO: default conv = conv2d?
# TODO: default strides = 1, padding='SAME'
# TODO: regularization

layers:
  embedding:
    type: 'embedding'
    options:
      input_dim: 20000
      output_dim: 128
  lstm_1:
    type: 'LSTM'
    options:
      units: 128
      dropout: 0.2
      recurrent_dropout: 0.2
      activation:
        type: 'tanh'
  dense_3_output:
    type: 'dense'
    options:
      units: 1
      activation:
        type: 'sigmoid'
