overall:
  name: 'sentiment_imdb'
  loss_fn: 'sigmoid'
  experiment_dir: 'trial_01' # will make + /best_params/ and + /tf_logs/ + /yf_logs/
  saver:
    save_params_name: "best_params_saver"
  # trace: Null
  logging:
    console:
      level: 'critical'
      format_str: null
    file:
      level: 'debug'
      format_str: null
    graph_spec: True
  metrics: 
    type: 'classification'
  num_classes: 1 # TODO: this should be inferred for sigmoid
data:
  in: 
    dim: [256]
    dtype: 'int64' # this is weird...
  label:
    dim: [1]
    dtype: 'int64' # TODO: should default to parse value of TRF
  TFR_parse:
    feature:
      name: "/features"
      dtype: "int64" # what to decode it to # TODO: should default to same
      tftype: "FixedLenSequenceFeature"
      in_type: "int64"
    label:
      name: "/label"
      dtype: "int64" # what to decode it to
      tftype: "fixedlenfeature"
      in_type: "int64" # what it is encoded as
  TFR:
    dir: './examples/sentiment_imdb/data/'
    train: 'train.tfrecords'
    validation: 'val.tfrecords'
    test: 'test.tfrecords'
hyper_parameters:
  optimizer: 'adam'
  lr: 0.0001
  batch_size: 32
  epochs: 10
  default_activation: 'elu'
  shuffle_buffer: 128
  # early_stopping:
  #   epochs: 3
  #   warm_up_epochs: 5
hidden:
  yaml: './examples/sentiment_imdb/hidden_config.yaml'
