# all paths are relative to yaml/execution?
# TODO: naming/structure will need to be improved
meta:
  name: 'cats_v_dogs'
  experiment_dir: 'trial_01'
  saver:
    save_params_name: "best_params_saver"

logging:
  console:
    level: 'info'
    format_str: null
  file:
    level: 'debug'
    format_str: null
  graph_spec: True

performance:
  loss_fn: 
    type: 'binary_crossentropy'
  type: ["BinaryAccuracy"]

data:
  in: 
    dim: [150, 150, 3]
    dtype: 'float32'
  label:
    dim: [1]
    dtype: 'int64'
  TFR_parse:
    feature:
      name: "/image"
      dtype: "float32"
      tftype: "fixedlenfeature"
      in_type: "string"
    label:
      name: "/label"
      dtype: "int64" # what to decode it to
      tftype: "fixedlenfeature"
      in_type: "int64" # what it is encoded as
  TFR:
    dir: './examples/cats_v_dogs/data/record_holder/150'
    train: 'train.tfrecords'
    validation: 'val.tfrecords'
    test: 'test.tfrecords'
  # image:
  #   standardize: True
  #   augmentation:
  #     aug_val: True
  #     v_flip: True
  #     h_flip: True
  #     #rotate: 0
  #     max_brightness: 0.2

hyper_parameters:
  optimizer: 
    type: 'adam'
    learning_rate: 0.001
  batch_size: 32
  epochs: 3
  shuffle_buffer: 128
  # early_stopping:
  #   epochs: 3
  #   warm_up_epochs: 5

model:
  path: './examples/cats_v_dogs/model_config.yaml'