# documentation will be key - "sane" defaults
# key: value
# key will be the "name" of the layer, value will hold the type+
# TODO: set *NECESSARTY/REQUIRED* params

# TODO: initialization
# TODO: option to write scalar
# TODO: default conv = conv2d?
# TODO: default strides = 1, padding='SAME'
meta:
  activation:
    type: 'relu'
    max_value: 6


layers:
  batch_norm_0:
    type: 'batchnormalization'
  conv_1:
    type: 'conv2d'
    options:
      filters: 16
      kernel_size: 3
      strides: 2
      activation:
        type: 'elu'
  batch_norm_1:
    type: 'batchnormalization'
  pool_1:
    type: 'AveragePooling2D'
    options:
      pool_size: 2
      strides: 2
  conv_2:
    type: 'conv2d'
    options:
      filters: 32
      kernel_size: 3
      strides: 1
  batch_norm_2:
    type: 'batchnormalization'
  pool_2:
    type: 'AveragePooling2D'
    options:
      pool_size: 2
      strides: 2
  conv_3:
    type: 'conv2d'
    options:
      filters: 64
      kernel_size: 3
      strides: 1
  batch_norm_3:
    type: 'batchnormalization'
  pool_3:
    type: 'MaxPooling2D'
    options:
      pool_size: 2
      strides: 2
  dropout_1:
    type: 'dropout'
    options:
      rate: 0.5
  flatten_1:
    type: 'flatten'
  dense_1:
    type: 'dense'
    options:
      units: 64
  dropout_2:
    type: 'dropout'
    options:
      rate: 0.5
  batch_norm_4:
    type: 'batchnormalization'
  dense_2:
    type: 'dense'
    options:
      units: 16
  dropout_1:
    type: 'dropout'
    options:
      rate: 0.5
  dense_out:
    type: 'dense'
    options:
      units: 1
      activation:
        type: 'sigmoid'