name: "model_a"
start_fresh: True

# TODO: it could be assumed that if only one layer in is defined in main, that
# it could be the `in_name` to the first layer.
layers:
  # backbone
  conv_1:
    type: 'conv2d'
    options:
      filters: 8
      kernel_size: 3
      padding: "same"
    in_name: 'image_in'
  conv_2_downsample:
    type: 'conv2d'
    options:
      filters: 8
      kernel_size: 3
      strides: 2
      padding: "same"
    # in_name: 'feature_a'
  conv_3:
    type: 'conv2d'
    options:
      filters: 8
      kernel_size: 3
      strides: 1
      padding: "same"
  conv_4_downsample:
    type: 'conv2d'
    options:
      filters: 8
      kernel_size: 3
      strides: 2
      padding: "same"
  flatten_1:
    type: 'flatten'
  dense_1:
    type: 'dense'
    options:
      units: 128
      activation:
        type: 'elu'

  # mnist head
  dense_mnist:
    type: 'dense'
    options:
      units: 32
      activation:
        type: 'elu'
    in_name: 'dense_1'
  dense_fashion_mnist:
    type: 'dense'
    options:
      units: 32
      activation:
        type: 'elu'
    in_name: 'dense_1'
  mnist_pred:
    type: 'dense'
    options:
      units: 10
      activation:
        type: 'softmax'
    in_name: "dense_mnist"
    endpoint: True
  fashion_mnist_pred:
    type: 'dense'
    options:
      units: 10
      activation:
        type: 'softmax'
    in_name: "dense_fashion_mnist"
    endpoint: True
