layers:
  conv_1:
    type: 'conv2d'
    options:
      filters: 16
      kernel_size: 3
      strides: 2
      padding: 'same'
  conv_2:
    type: 'conv2d'
    options:
      filters: 32
      kernel_size: 3
      strides: 2
      padding: 'same'
  conv_3:
    type: 'conv2d'
    options:
      filters: 32
      kernel_size: 3
      strides: 2
      padding: 'same'
  conv_4:
    type: 'conv2d'
    options:
      filters: 64
      kernel_size: 3
      strides: 1
  deconv_1:
    type: 'Conv2DTranspose'
    options:
      filters: 32
      kernel_size: 3
      strides: 1
  deconv_2:
    type: 'Conv2DTranspose'
    options:
      filters: 32
      kernel_size: 3
      strides: 2
      padding: 'same'
  deconv_3:
    type: 'Conv2DTranspose'
    options:
      filters: 16
      kernel_size: 3
      strides: 2
      padding: 'same'
  deconv_4:
    type: 'Conv2DTranspose'
    options:
      filters: 1
      kernel_size: 3
      strides: 2
      padding: 'same'
      activation: 
        type: 'linear'