# documentation will be key - "sane" defaults
# key: value
# key will be the "name" of the layer, value will hold the type+
# TODO: set *NECESSARTY/REQUIRED* params

# TODO: initialization
# TODO: option to write scalar
# TODO: default conv = conv2d?
# TODO: default strides = 1, padding='SAME'
# TODO: regularization

layers:
  conv_1:
    type: 'conv2d'
    options:
      filters: 32
      kernel_size: 3
      strides: 1
      trainable: False
    #saver:
      #load_params: True # default is False
      #load_path: null # in case the default is not usable - TODO: implement logic
      #load_name: null # in case of (likely) different names, current name is default
  conv_2:
    type: 'conv2d'
    options:
      filters: 64
      kernel_size: 3
      strides: 1
      trainable: True
    #saver:
      #load_params: True
  dropout_1:
    type: 'dropout'
    options:
      rate: 0.5
  pool_1:
    type: 'pooling2d'
  flatten_1:
    type: 'flatten'
  dense_1:
    type: 'dense'
    options:
      units: 16
      dropout: 0.5
      trainable: True
    #saver:
      #load_params: True