meta:
  name: 'mnist'
  experiment_dir: 'trial_01'
  # TODO: information on when to save params, currently only best params saved
logging:
  console:
    level: 'info'
    format_str: null
  file:
    level: 'ERROR'
    format_str: null
  graph_spec: True

performance:
  loss_fn: 
    type: 'categorical_crossentropy'
  type: ["MeanSquaredError", "TopKCategoricalAccuracy", "CategoricalAccuracy"]
  options: [null, 
            {"k": 2}, 
            null]

# TODO: this section needs to be redone
data:
  in:
    dim: [784]
    dtype: 'float32'
    reshape_to: [28, 28, 1]
  label:
    dim: [10]
    dtype: 'float32'
    one_hot: True # TODO: ensure this is being used
  TFR_parse:
    feature:
      name: "/image"
      dtype: "int8"
      tftype: "fixedlenfeature"
      in_type: "string"
    label:
      name: "/label"
      dtype: "int64" # what to decode it to
      tftype: "fixedlenfeature"
      in_type: "int64" # what it is encoded as
  TFR:
    dir: './examples/mnist/data/'
    train: 'train.tfrecords'
    validation: 'validation.tfrecords'
    test: 'test.tfrecords'

hyper_parameters:
  optimizer: 
    type: 'adam'
    learning_rate: 0.0001
  batch_size: 32
  epochs: 3
  shuffle_buffer: 128
model:
  path: './examples/mnist/model_config.yaml'

