# TODO: this should be the "architecture config"

# documentation will be key - "sane" defaults
# key: value
# key will be the "name" of the layer, value will hold the type+
# TODO: set *NECESSARTY/REQUIRED* params

# TODO: initialization
# TODO: option to write scalar
# TODO: default conv = conv2d?
# TODO: default strides = 1, padding='SAME'
# TODO: regularization
meta:
  activation:
    type: 'relu'
    max_value: 6

layers:
  conv_1:
    type: 'conv2d'
    options:
      filters: 32
      kernel_size: 3
      strides: 1
      trainable: False
      activation:
        type: 'relu'
        max_value: 6
    #saver:
      #load_params: True # default is False
      #load_path: null # in case the default is not usable - TODO: implement logic
      #load_name: null # in case of (likely) different names, current name is default
  conv_2:
    type: 'conv2d'
    options:
      filters: 64
      kernel_size: 3
      strides: 1
      trainable: True
      kernel_initializer: 
        type: "glorot_normal"
        options:
          seed: 42
      activation: 
        type: 'relu'
    #saver:
      #load_params: True
  dropout_1:
    type: 'dropout'
    options:
      rate: 0.5
  pool_1:
    type: 'AveragePooling2D'
    options:
      pool_size: 2
      strides: 2
  flatten_1:
    type: 'flatten'
  dense_1:
    type: 'dense'
    options:
      units: 32
      kernel_regularizer:
        type: 'l1'
        l: 0.001
  dense_2_output:
    type: 'dense'
    options:
      units: 10
      activation:
        type: 'softmax'
    #saver:
      #load_params: True